### ISSUE TITLE
unexpected r interface outputs 

### ISSUE THREAD

**Issue by yao-yl** [bob-carpenter/stan-model-server#5]
I played with the R interface, it is so cool! (a minor issue: the R interface needs to add dependence on the package `rjson`)

One confusion I have is the returned names of param_unconstrain(). 

It seems that the constrained parameter has names and are designed as a list. For example, I can do `param_unconstrain(param_list = list(theta = 0.6))`.

But the unconstrained parameters do not have names? 
If the unconstrained parameters do have names, say "theta_ unconstrained", then I imagine that I can call the following line?
`param_constrain(list(theta_ unconstrained = -8))`

**Comment by bob-carpenter** [comment]
The `param_unconstrain` function takes a structured list of parameters and returns a flat vector of unconstrained parameters.  You use the constrained names of the parameters there.

The `param_constrain` function just takes an array of unconstrained parameters and returns an array of constrained parameters.  the param_names function gives you the names (with indexes) of the parameters.

**Comment by bob-carpenter** [comment]
Can you submit a PR to fix the dependence on `rjson`?  Is that just something in the doc or does some code need to change?

**Comment by yao-yl** [comment]
It takes me a while to figure our that to run the R interface, I need to first make the stan file in stan-model-server. This is slightly confusing because the make output is the seemingly same .cpp file from cmdstan. I assume we can also add this make stan-model-server into the R interface.

**Comment by yao-yl** [comment]
One more issue regarding the R interface; below is a replication example.

I am making a test on this simple stan model, save this as 'foo.stan':

```
data {
  int d;
}
parameters {
  real mu[d];
  real logsigma[d];
  real theta[d];
}
transformed parameters {
  real sigma[d] = exp(logsigma);
}
model {
  target += normal_lpdf(theta | mu, sigma);
}
```

The model only computes normal_lpdf(theta | mu, sigma); that is it. 


Now in R interface, I generate data and run model server:


```
d=1
data <- list(d=d)
datefile=("foo.json") 
cmdstanr::write_stan_json(data, datefile)

source('StanModelClient.R')
server <- "foo"          # path to executable
sc <- create_stan_client(server, datefile, seed=1234)
```

Then I run into some unexpected results:
```
sc$param_unconstrain(param_list=list(mu=1, logsigma=1,theta=3))
 ```
it returns 
```
[1] 1 1 3
```
That is right, because all parameters are already unconstrained. 


But if I go back to the constrained parameters from these unconstrained ones, it goes wrong:

```
sc$param_constrain(c(1,1,3),tp = FALSE, gq = FALSE)
```
Current output:
```
[1] 1 0 0
```
expected output:

```
[1] 1 1 3
```

**Comment by WardBrian** [comment]
The above model does the right thing in the python wrapper, returning `[1, 1, 3]` for both constraining and unconstraining

**Comment by bob-carpenter** [comment]
Thanks for verifying, @WardBrian.

@yao-yl :  Could you take a shot at fixing the R code and submitting a pull request? You should be able to copy what the Python interface does.
